print("hello world", end=' ')
print("hello again", end=' ')
print("i like typing this.", end=' ')
print("this is fun.", end=' ')
print('yay! printing.', end=' ')
print("I'd much rather you 'not'.", end=' ')
print('I "said" do not touch this.', end=' ')
